export const SET_WORD_COUNT = 'SET_WORD_COUNT'
export const SET_DOC_INFO = 'SET_DOC_INFO'
export const UPDATE_TEXT = 'UPDATE_TEXT'
export const SET_INVOICE = 'SET_INVOICE'
export const UPDATE_READ_COUNT = 'UPDATE_READ_COUNT'
export const SET_PUB_KEY = 'SET_PUB_KEY'
export const SET_AES_KEY = 'SET_AES_KEY'
